#!/usr/bin/env python
#
# elgamal - Elgamal with elliptic curve.
# Version 1.0
# Year 2014
# Author Alexandre PUJOL <alexandre.pujol.1@etu.univ-amu.fr>
# Author Maxime CHEMIN <maxime.chemin@etu.univ-amu.fr>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License.
#

import argparse
import sys
from ecurve.tools import *
from ecurve.elliptic import EllipticCurve
from ecurve.elgamal import Elgamal


""" Generate Elgamal keys
 Input :
 - Curve (default : curves/w256-001.gp)
 Output :
 - Public key (default : keys/elgamal.pub)
 - Private key (default : keys/elgamal)
"""
def Keygen():
   print(":: Keygen")
   
   if arg.key is not False or arg.input is not False:
      raise Exception('Argument error')
   
   if arg.curve is False:
      arg.curve = 'curves/w256-001.gp'

   if arg.output is False:
      arg.output = 'keys/elgamal'
      
   print(" Loading the curve : " + arg.curve)
   curve = tools.loadCurve(arg.curve)
   
   elgamal = Elgamal(curve)
   
   print(" Generating Elgamal keys")
   (publickey, privatekey) = elgamal.keygen()
   
   print(" Writing Elgamal keys")
   print("  - Public key  : " + arg.output + ".pub")
   key.writeKey(arg.output + '.pub', 'ELGAMAL', curve, publickey)
   print("  - Private key : " + arg.output)
   key.writeKey(arg.output, 'ELGAMAL', curve, privatekey)



""" Encryption
 Input :
 - Public key (default : keys/elgamal.pub)
 - Message (default : sample/text)
 Output :
 - Encoded message (default : sample/text.elgamal)
""" 
def Encryption():
   print(":: Encryption")
   
   if arg.curve is not False:
      raise Exception('Argument error')
   
   if arg.key is False:
      arg.key = 'keys/elgamal.pub'
   
   if arg.input is False:
      arg.input = 'sample/text'

   if arg.output is False:
      arg.output = 'sample/text.elgamal'
      
   print(" Reading the public key : " + arg.key)
   (curve, publickey) = key.readKey(arg.key)
   
   print(" Encypting :")
   print(" - Input file  : " + arg.input)
   print(" - Output file : " + arg.output)
   elgamal = Elgamal(curve)
   with open(arg.input, "rb") as file:
      with open(arg.output, 'w') as cipher:
         buffer_size = 35
         byte = file.read(buffer_size)
         while byte:
            m = int.from_bytes(byte, sys.byteorder)
            (c1, c2) = elgamal.encrypt(publickey, m)
            cipher.write(str(c1)+ "\n")
            cipher.write(str(c2.x)+ "\n")
            cipher.write(str(c2.y)+ "\n")
            byte = file.read(buffer_size)
         cipher.close()
      file.close()


""" Decryption elgamal cipher
 Input :
 - Private key (default : keys/elgamal)
 - Encoded message (default : sample/text.elgamal)
 Output :
 - Message (default : sample/text.decoded)
"""
def Decryption():
   print(":: Decryption")
   
   if arg.curve is not False:
      raise Exception('Argument error')
      
   if arg.key is False:
      arg.key = 'keys/elgamal'
   
   if arg.input is False:
      arg.input = 'sample/text.elgamal'

   if arg.output is False:
      arg.output = 'sample/text.decoded'
      
   print(" Reading the private key : " + arg.key)
   (curve, privatekey) = key.readKey(arg.key)
   
   print(" Decryption :")
   print(" - Input file  : " + arg.input)
   print(" - Output file : " + arg.output)
   elgamal = Elgamal(curve)
   with open(arg.input, "r") as cipher:
      with open(arg.output, 'wb') as file:
         lines = cipher.readlines()
         ii = 0
         while ii < len(lines):
            c2 = Point(curve, int(lines[ii + 1]), int(lines[ii + 2]))
            m = elgamal.decrypt(privatekey, int(lines[ii]), c2)
            file.write(m.to_bytes(m.bit_length()//8 + 1, sys.byteorder))
            ii += 3
         file.close()
      cipher.close()
      
      
parser = argparse.ArgumentParser(description='Elgamal with elliptic curve.')
parser.add_argument( '-K','--keygen',
                     action='store_const', dest='prgm', const='keygen',
                     help='Generate Elgamal keys pair')
parser.add_argument( '-C', '--crypt', 
                     action='store_const', dest='prgm', const='crypt',
                     help='Encryption mode')
parser.add_argument( '-D', '--decrypt', 
                     action='store_const', dest='prgm', const='decrypt',
                     help='Decryption mode')
parser.add_argument( '-c', '--curve',
                     action='store', default=False, dest='curve',
                     help='Load a specific elliptic curve')
parser.add_argument( '-k', '--key',
                     action='store', default=False, dest='key',
                     help='Load an Elgamal key (public or private)')
parser.add_argument( '-i', '--input',
                     action='store', default=False, dest='input',
                     help='File input')
parser.add_argument( '-o', '--output',
                     action='store', default=False, dest='output',
                     help='File output')
parser.add_argument( '-v', '--version', 
                     action='version', version='%(prog)s 1.0')
arg = parser.parse_args()

if arg.prgm is 'keygen':
   Keygen()
elif arg.prgm is 'crypt':
   Encryption()
elif arg.prgm is 'decrypt':
   Decryption()
else:
   raise Exception('Argument error')
   
