#!/usr/bin/env python
#
# elgamal - Elgamal with elliptic curve.
# Version 1.0
# Year 2014
# Author Alexandre PUJOL <alexandre.pujol.1@etu.univ-amu.fr>
# Author Maxime CHEMIN <maxime.chemin@etu.univ-amu.fr>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License.
#

import argparse
from tools import *
from elliptic import *
from elgamal import *


""" Generate Elgamal keys
 Input :
 - Curve (default : curves/w256-001.gp)
 Output :
 - Public key (default : keys/elgamal.pub)
 - Private key (default : keys/elgamal)
"""
def Keygen():
   print(":: Keygen")
   
   if arg.key is not False or arg.input is not False:
      raise Exception('Argument error')
   
   if arg.curve is False:
      arg.curve = 'curves/w256-001.gp'

   if arg.output is False:
      arg.output = 'keys/elgamal'
      
   print(" Loading the curve : " + arg.curve)
   curve = tools.loadCurve(arg.curve)
   
   elgamal = Elgamal(curve)
   
   print(" Generating Elgamal keys")
   (publickey, privatekey) = elgamal.keygen()
   
   print(" Writing Elgamal keys")
   print("  - Public key  : " + arg.output + ".pub")
   key.writeKey(arg.output + '.pub', 'ELGAMAL', curve, publickey)
   print("  - Private key : " + arg.output)
   key.writeKey(arg.output, 'ELGAMAL', curve, privatekey)



""" Crypt message
 Input :
 - Public key (default : keys/elgamal.pub)
 - Message (default : sample/text)
 Output :
 - Encoded message (default : sample/text.elgamal)
""" 
def Crypt():
   print(":: Crypt")
   
   if arg.curve is not False:
      raise Exception('Argument error')
   
   if arg.key is False:
      arg.key = 'keys/elgamal.pub'
   
   if arg.input is False:
      arg.input = 'sample/text'

   if arg.output is False:
      arg.output = 'sample/text.elgamal'
      
   print(" Reading the public key : " + arg.key)
   (curve, publickey) = key.readKey(arg.key)
   
   print(" Reading the mesage : " + arg.input)
   m = tools.readFile(arg.input)
      
   print(" Crypt the message")
   elgamal = Elgamal(curve)
   (c1, c2) = elgamal.encrypt(publickey, m)    
   
   print(" Writing the encrypted message : " + arg.output)
   c = str(c1) + "\n" + str(c2.x) + "\n" + str(c2.y)
   tools.writeFile(arg.output, c)



""" Decrypt elgamal message
 Input :
 - Private key (default : keys/elgamal)
 - Encoded message (default : sample/text.elgamal)
 Output :
 - Message (default : sample/text.decoded)
"""
def Decrypt():
   print(":: Decrypt")
   
   if arg.curve is not False:
      raise Exception('Argument error')
      
   if arg.key is False:
      arg.key = 'keys/elgamal'
   
   if arg.input is False:
      arg.input = 'sample/text.elgamal'

   if arg.output is False:
      arg.output = 'sample/text.decoded'
      
   print(" Reading the private key : " + arg.key)
   (curve, privatekey) = key.readKey(arg.key)
   
   print(" Reading the encrypted message : " + arg.input)
   c = tools.readFile(arg.input)
   c1 = int(c.split('\n')[0])
   c2 = Point(curve, int(c.split('\n')[1]), int(c.split('\n')[2]))
   
   print(" Decrypt the message")
   elgamal = Elgamal(curve)
   m = elgamal.decrypt(privatekey, c1, c2)
   
   print(" Writing the decrypted message")
   tools.writeFile(arg.output, str(m))


parser = argparse.ArgumentParser(description='Elgamal with elliptic curve.')
parser.add_argument( '-K','--keygen',
                     action='store_const', dest='prgm', const='keygen',
                     help='Generate Elgamal keys pair')
parser.add_argument( '-C', '--crypt', 
                     action='store_const', dest='prgm', const='crypt',
                     help='Encryption mode')
parser.add_argument( '-D', '--decrypt', 
                     action='store_const', dest='prgm', const='decrypt',
                     help='Decryption mode')
parser.add_argument( '-c', '--curve',
                     action='store', default=False, dest='curve',
                     help='Load a specific elliptic curve')
parser.add_argument( '-k', '--key',
                     action='store', default=False, dest='key',
                     help='Load an Elgamal key (public or private)')
parser.add_argument( '-i', '--input',
                     action='store', default=False, dest='input',
                     help='File input')
parser.add_argument( '-o', '--output',
                     action='store', default=False, dest='output',
                     help='File output')
parser.add_argument( '-v', '--version', 
                     action='version', version='%(prog)s 1.0')
arg = parser.parse_args()

if arg.prgm is 'keygen':
   Keygen()
elif arg.prgm is 'crypt':
   Crypt()
elif arg.prgm is 'decrypt':
   Decrypt()
else:
   raise Exception('Argument error')
   
