#!/usr/bin/env python
#
# sts - STS with elliptic curve.
# Version 1.0
# Year 2014
# Author Alexandre PUJOL <alexandre.pujol.1@etu.univ-amu.fr>
# Author Maxime CHEMIN <maxime.chemin@etu.univ-amu.fr>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License.
#

import argparse
import socket
from elliptic import *
from tools import *
from STS import *
import struct

""" Generate STS key (same than DH key)
 Input :
 - Curve (default : curves/w256-001.gp)
 Output :
 - Private key (default : keys/sts)
"""
def Keygen():
   print(":: Keygen")
   
   if arg.key is not False or arg.host is not False :
      raise Exception('Argument error')
   if arg.host is not False or arg.port is not False:
      raise Exception('Argument error')
      
   if arg.curve is False:
      arg.curve = 'curves/w256-001.gp'

   if arg.output is False:
      arg.output = 'keys/sts'
      
   print(" Load curve : " + arg.curve)
   curve = tools.loadCurve(arg.curve)
   
   sts = STS(curve)
   
   print(" Generate key")
   x = sts.keygen()
   
   print(" Write private STS key : " + arg.output)
   key.writeKey(arg.output, 'DIFFIEHELLMAN', curve, x)
   
   
""" Share
 Input :
 - Private key (default : keys/sts)
 - Host (default : localhost)
 - Host's port (default : 12800)
 Output :
 - Shared secret (default : keys/sts.shared)
"""
def Share():
   print(":: Share key")
   
   if arg.curve is not False:
      raise Exception('Argument error')
      
   if arg.key is False:
      arg.key = 'keys/sts'
      
   if arg.host is False:
      arg.host = 'localhost'
      
   if arg.port is False:
      arg.port = 12800
   else:
      arg.port = int(arg.port)
      
   if arg.output is False:
      arg.output = 'keys/sts.shared'
            
   print(" Read privatekey key : " + arg.key)
   (curve, x) = key.readKey(arg.key)
   
   sts = STS(curve)
   
   print(" Compute : g^x")
   gx = sts.secret(x)
   gx_bytes = (str(gx.x) + "," + str(gx.y)).encode()
   
   ecdsa_keys = 'keys/ecdsa' # TODO : Add an arg for that
   print(" Read ECDSA keys (certificat) : " + ecdsa_keys + ".pub")
   (curve2, ecdsa_publickey) = key.readKey(ecdsa_keys + ".pub")
   (curve3, ecdsa_privatekey) = key.readKey(ecdsa_keys)
   if curve != curve2 or curve != curve3:
      print (curve.p,curve.n,curve.a4,curve.a6) == (curve2.p,curve2.n,curve2.a4,curve2.a6)

      raise Exception('ECDSA keys are not on the same curve than DH secret')
   certificat_bytes = (str(ecdsa_publickey.x)+","+str(ecdsa_publickey.y)).encode()
   
   # TODO : For now we suppose Alice and Bob has got the same curve. 
   #        Therefore we will have to send the curve with socket too.
   # TODO : We can optimise this. Less code for same prgm
   if arg.server is True:
      # There is no server yet. We create it
      server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
      server.bind(('', arg.port))
      server.listen(1)
      
      print(" Server started")
      print(" Waiting for client connection...")
      (server_to_client, address) = server.accept()
      
      print(" Server connected to : " + str(address))
      print(" Sending secret to client->gx")
      server_to_client.send(gx_bytes)
      
      print(" gy<-Getting client's secret")
      gy_bytes = server_to_client.recv(4096)
      
      print(" Compute : Signed and encrypt it")
      gy_str = gy_bytes.decode()
      (gy_str_x, gy_str_y) = gy_str.split(',')
      gy = Point(curve, int(gy_str_x), int(gy_str_y))
      (K, encrypted, iv) = sts.sharedsecret(ecdsa_privatekey, x, gx, gy)
      
      print(" Sending to client :")
      print("  - Public key certificate->cert")
      server_to_client.send(certificat_bytes)
      print("  - Signature encrypted->sign")
      length = struct.pack('!I',len(encrypted))
      server_to_client.send(length+encrypted)
      
      length = struct.pack('!I',len(iv))
      res = server_to_client.send(length+iv)
      print (len(iv))
      print(res)
      print(" <-Getting from the client :")
      print("  - Public key certificate")
      certificat_bytes = server_to_client.recv(4096)
      print("  - Signature encrypted")
      signed_encrypted_bytes = server_to_client.recv(4096)
      
      print(" Closing connection")
      server_to_client.close()
      server.close()
   else:
      # There is a server. We connect to it
      client_to_server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
      client_to_server.connect((arg.host, arg.port))
      print(" Connected to : " + arg.host + " on port " + str(arg.port))

      print(" Getting server's secret")
      gy_bytes = client_to_server.recv(1024)
      
      print(" Sending secret to server")
      client_to_server.send(gx_bytes)
      
      print(" Compute : Signed and encrypt it")
      gy_str = gy_bytes.decode()
      (gy_str_x, gy_str_y) = gy_str.split(',')
      gy = Point(curve, int(gy_str_x), int(gy_str_y))
      (K, encrypted, iv) = sts.sharedsecret(ecdsa_privatekey, x, gx, gy)

      print(" Getting from the server :")
      print("  - Public key certificate")
      certificat_bytes = client_to_server.recv(4096)
      print("  - Signature encrypted")
      #Get size of the message
      l = client_to_server.recv(4)
      l_buff = struct.unpack('!I',l)[0]
      
      encrypted = client_to_server.recv(l_buff)
      
      l = client_to_server.recv(4)
      l_buff = struct.unpack('!I',l)[0]
      iv = client_to_server.recv(l_buff)
      
      print(" Sending to the server :")
      print("  - Public key certificate")
      res = client_to_server.send(certificat_bytes)

      print("  - Signature encrypted")
      client_to_server.send(encrypted)
      client_to_server.send(iv)
      
      print(" Closing connection")
      client_to_server.close()
   
      
   print(" Verification")
   
   print(" Write shared secret in " + arg.output)
   #key.writeKey(arg.output, 'DIFFIEHELLMAN', curve, gxy)
   

parser = argparse.ArgumentParser(description='Diffie Hellman with elliptic curve.')
parser.add_argument( '-K','--keygen',
                     action='store_const', dest='prgm', const='keygen',
                     help='Generate STS private key')
parser.add_argument( '-S', '--share',
                     action='store_const', dest='prgm', const='share',
                     help='Share key with an other computer')
parser.add_argument( '-c', '--curve',
                     action='store', default=False, dest='curve',
                     help='Load a specific elliptic curve ')
parser.add_argument( '-k', '--key',
                     action='store', default=False, dest='key',
                     help='Load  key')
parser.add_argument( '--host',
                     action='store', default=False, dest='host',
                     help='Hostname or IP of the other computer')
parser.add_argument( '--port',
                     action='store', default=False, dest='port',
                     help='Hostname\'s port')
parser.add_argument( '-o', '--output',
                     action='store', default=False, dest='output',
                     help='Output file')
parser.add_argument( '-s', '--server',
                     action='store_true', default=False, dest='server',
                     help='Create server connection')
parser.add_argument( '-v', '--version', 
                     action='version', version='%(prog)s 1.0')
arg = parser.parse_args()

if arg.prgm is 'keygen':
   Keygen()
elif arg.prgm is 'share':
   Share()
else:
   raise Exception('Argument error')
   
